### ISSUE TITLE
PolygonRepair::insertConstraints: Cannot understand input. Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ldemaz** [tudelft3d/prepair#16]
Hi there, 
I have incorporated prepair and pprepair as cleaning utilities (called via python scripts) as cleaning utilities for a postgis database.  

I found the above mentioned error with the following wkt, which I can't understand.  

prepair --wkt 'POLYGON((30.2101265604148 -25.5694229047629,30.2094828302513 -25.5711649475588,30.2125727350371 -25.5716101322077,30.2128516847743 -25.5694616171007,30.2101265604148 -25.5694229047629))' --minarea 0.000000001

Looking at the plotted polygon, it seems to be fairly standard.  Any pointers on this will be welcome!

Thanks!

**Comment by ldemaz** [comment]
We managed to fix this--it turns out that a local install of gdal on our server, which messed up paths, was the cause.

**Comment by kenohori** [comment]
Glad to hear that!
