### ISSUE TITLE
User-defined output folder and file name

### ISSUE THREAD

**Issue by fdetsch** [tudelft3d/prepair#21]
When dealing with OGR datasets in combination with `--shOut`, it would be great to be able to specify both the output folder and file name, which currently defaults to 'out.shp'. As concerns the command-line interface (I haven't checked the QGIS plug-in so far), do you plan to implement such functionality?

**Comment by kenohori** [comment]
First of all, sorry for the long delay! You can specify complete paths in branch improvements-with-ogr, which should become the main branch after we're able to do some more testing.
