### ISSUE TITLE
Consider supporting Multipolygons

### ISSUE THREAD

**Issue by peterneubauer** [tudelft3d/prepair#24]
Hi there,
when trying to repair the geometry in https://raw.githubusercontent.com/whosonfirst/whosonfirst-data/master/data/856/820/41/85682041.geojson, I extract it to a file and run

    ../prepair/prepair --ogr tmp.json
    First feature ain't a POLYGON.

Would it be hard to support `MYLTIPOLYGON`?

**Comment by kenohori** [comment]
Hi Peter,

Try branch improvements-with-ogr. That one has full support for multipolygons.

**Comment by peterneubauer** [comment]
Thanks a lot!
