### ISSUE TITLE
Windows binary for improvements-with-ogr?

### ISSUE THREAD

**Issue by lukemac1** [tudelft3d/prepair#25]
How difficult would it be to create a windows binary for the improvements-with-ogr branch?

**Comment by tcommandeur** [comment]
This can be done easily as I did it using Visual Studio 2015/1017 Community Edition. First get the boost binaries, then download CGAL source, build CGAL and finally get the GDAL binaries. Then set the directories in the windows path and use CMAKE to create the Visual Studio solution and project.
