### ISSUE TITLE
prepair v2

### ISSUE THREAD

**Issue by dickoa** [tudelft3d/prepair#36]
Hi @kenohori ,

I hope all is good, I noticed that you worked a new version of prepair and really happy to see that you had time to work on it again.
I was checking if this version is final enough to be used or you'll work on it in the future. I'm still using v1 and wanted to check if it was move my R package from v1 to v2 or wait before submitting to CRAN.

Thanks again,
Ahmadou

**Comment by kenohori** [comment]
Hi @dickoa,

Thanks for the message! Sorry, but I haven't had the time to finish the v2 release yet. I need to work on other projects for the next few months, so feel free to submit using v1. The v2 API will be basically the same, so it should be easy to adapt it later.

**Comment by dickoa** [comment]
Thanks a lot for your work on this, I will push it CRAN after some testing.
Thanks again and have a nice day!
Ahmadou

**Comment by kenohori** [comment]
Thanks to you for the submission!
